### ISSUE TITLE
An image found not converted

### ISSUE THREAD

**Issue by tiye** [thenittygritty/feedback#1]
Search "The compiled buttons" at http://thenittygritty.co/articles

**Comment by drublic** [comment]
Thanks for reporting. Where did you find the broken images? They should all be working as of now.

**Comment by tiye** [comment]
Check this:
![screen shot 2013-11-15 at 11 08 54 am](https://f.cloud.github.com/assets/449224/1547529/4deae0de-4da3-11e3-9942-8782b3c687f0.png)

**Comment by drublic** [comment]
Thanks for the pointer. This is fixed and will be live with the next release (tomorrow).
