### ISSUE TITLE
mobile layout: content too small, footer breaks page

### ISSUE THREAD

**Issue by anselmh** [thenittygritty/feedback#2]
![2013-11-17 19 59 13](https://f.cloud.github.com/assets/399345/1561199/d592c0d2-5029-11e3-9967-47211f7e49dc.png)
![2013-11-17 19 59 21](https://f.cloud.github.com/assets/399345/1561200/d5934b24-5029-11e3-9570-09e49f8624e3.png)

**Comment by drublic** [comment]
Thanks for reporting. Fixed with drublic/tng@430da2d4a08376172e217f16528ab11179a7662c and will be live pretty soon ;)
