### ISSUE TITLE
mobile layout: images still floated

### ISSUE THREAD

**Issue by anselmh** [thenittygritty/feedback#3]
On mobile, images in the content are resized and still floated. This often results in ugly and too tiny text lines as well as unrecognizable content of the images.
I suggest to not float them on mobile and give them `width: 100%`. Otherwise consider a modal window for them to be able to zoom the images.

**Comment by khalillechelt** [comment]
Yep! This needs to be fixed. Thanks for the reminder. @drublic do you have time for this before you publish the init article?

**Comment by drublic** [comment]
Yes, I think I can fix this.
Will try to look into it tomorrow.

**Comment by drublic** [comment]
Thanks, fixed in drublic/tng@f9e6ba158365075b011e8db1a75fa101d99723d0.
