### ISSUE TITLE
Make your browser work for you

### ISSUE THREAD

**Issue by jayzelenkov** [thenittygritty/feedback#5]
_update v1: added info about casperJS as an alternative to WebDriver-based API to communicate with browsers_

---
## TOC
- Goals of this article / talk
- Introduction
- Browsers explained (real, headless, unreal)
- e2e testing - pre-WebDriver (Selenium 1 and before)
- e2e testing - WebDriver API (Server <=> Client, Wire Protocol)
- e2e testing - WebDriver higher-level APIs => WebDriverJS.IO, Protractor, DalekJS
- _e2e testing - Non-WebDriver based - e.g. CasperJS_
### Goals
- Demo when integration tests can be useful
- Provide clarity & overview of testing tools & frameworks
### Introduction

**Main idea to communicate:** why to do E2E testing and what benefits one gets from doing so.
### Browsers explained

![browsers-explained](https://cloud.githubusercontent.com/assets/205659/2823145/b5812ccc-cf1b-11e3-9f9b-36f0a15d0ef0.png)

> mention when to use what of the above
### pre-WebDriver (Selenium 1 and before)

A little bit of history.

**Main idea to communicate:** Selenium 1 (and older tools) used record-and-replay approach, which proved to be inflexible.
### WebDriver API (Server <=> Client, Wire Protocol)

Overview of the WebDriver API. Explain that WebDriver API is based on Selenium 2.<br/> Show [Selenium's WebDriverJS wrapper](https://code.google.com/p/selenium/wiki/WebDriverJs) and how low-level it feels.

**Main ideas to communicate:** (1) Selenium uses Server and Client approach + REST-ful API. There is no way around it but it can be abstracted away from user. (2) WebDriver API is like `ANSI C`. There are higher-level frameworks available.
### WebDriver higher-level APIs => WebDriverJS.IO, Protractor, DalekJS

Explain approaches & limitations of each testing frameworks. _Code snippet is worth a thousand words._

**Main idea to communicate:** advantages of higher-level APIs. How they simplify tests and help to keep them maintainable.
### Non-WebDriver based - e.g. CasperJS

CasperJS sends commands directly to headless browsers (phantomjs, slimerjs).

**Main idea to communicate:** there are alternatives to WebDriver API. Advantages and limitations of headless browsers.

**Comment by jayzelenkov** [comment]
Hi TNG!

I got accepted as a speaker for FrankfurtJS and I will talk about integration tests for the front end. I would like to write an article to structure my thoughts and use it as a basis for the presentation. It will be my first talk ever and I don't want to screw it up :fearful:

**Comment by drublic** [comment]
Hi @jzelenkov.

I personally think it's a great topic for an article. I've come upon several tools for testing behavior and I like where your approach is going.
It would be great if you could add a small paragraph about WHY to do E2E testing and what benefits one gets form doing so even though this is clear to a lot of people.

Apart from that, it is fantastic that you use our platform to proof your ideas! I (and Kahlil sure too) really appreciate your engagement.

**Comment by jayzelenkov** [comment]
@drublic thanks for such a quick feedback. I've added your suggestion (explain why to do e2e) into the introduction section of the article outline.

What are my next actions? Shall I start writing and submit the first draft of the article when it is ready?

**Comment by khalillechelt** [comment]
@jzelenkov thanks for the submission! Yep yep just write the article and submit it as a pull request.
